base_url = "https://shorttechtakes.netlify.com/"
description = "Short takes on understanding tech these days as things move so fast... "
compile_sass = true
build_search_index = false
theme = "tabi"
title = "Short Tech Takes"
taxonomies = [{name = "tags", feed = true}]
#tags = ["skills", "productivity"]

[markdown]
highlight_code = true
highlight_theme = "css"


[extra]
# Put all your custom variables here

