base_url = "https://shorttechtakes.pages.dev/"
description = "Short takes on understanding tech these days as things move so fast... "
compile_sass = true
build_search_index = false
theme = "tabi"
title = "Short Tech Takes"
taxonomies = [{name = "tags", feed = true}]
#tags = ["skills", "productivity"]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
menu = [
    { name = "blog", url = "blog", trailing_slash = true },
   # { name = "archive", url = "archive", trailing_slash = true },
   # { name = "tags", url = "tags", trailing_slash = true },
   # { name = "projects", url = "projects", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
]
